/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_Test */

#ifndef _Included_test_Test
#define _Included_test_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_Test
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_Test_run
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
